version: '3.9'

services:
  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - wordpress_data1:/var/www/html
    networks:
      wordpress-net:
        ipv4_address: 172.20.0.11

  wordpress2:
    image: wordpress:latest
    container_name: wordpress2
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - wordpress_data2:/var/www/html
    networks:
      wordpress-net:
        ipv4_address: 172.20.0.12

  wordpress3:
    image: wordpress:latest
    container_name: wordpress3
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - wordpress_data3:/var/www/html
    networks:
      wordpress-net:
        ipv4_address: 172.20.0.13

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      wordpress-net:
        ipv4_address: 172.20.0.14

  load-balancer:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3
    networks:
      wordpress-net:
        ipv4_address: 172.20.0.20

volumes:
  wordpress_data1:
  wordpress_data2:
  wordpress_data3:
  db_data:

networks:
  wordpress-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
